DROP TABLE IF EXISTS TB_PRICE;
DROP TABLE IF EXISTS TB_BRAND;

CREATE TABLE TB_BRAND(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(250) NOT NULL
);

CREATE TABLE TB_PRICE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	BRAND_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL, 
	PRICE_LIST INT, 
	PRIORITY INT,
	PRICE DOUBLE NOT NULL,
	CURR VARCHAR(3) NOT NULL,
	FOREIGN KEY (BRAND_ID) REFERENCES TB_BRAND(ID)
);
